name: CI

on: [push, pull_request]

jobs:
  flatpak:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:7.1
      options: --privileged

    steps:
    - uses: actions/checkout@v2

    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
      with:
        bundle: Taxi.flatpak
        manifest-path: com.github.alecaddd.taxi.yml
        run-tests: true
        repository-name: appcenter
        repository-url: https://flatpak.elementary.io/repo.flatpakrepo
        cache-key: "flatpak-builder-${{ github.sha }}"
